#!/usr/bin/env python3

import logging

from .ioc_finder import (
    DEFAULT_IOC_TYPES,
    SUPPORTED_IOC_TYPES,
    find_iocs,
    parse_asns,
    parse_authentihashes_,
    parse_bitcoin_addresses,
    parse_complete_email_addresses,
    parse_cves,
    parse_domain_names,
    parse_email_addresses,
    parse_enterprise_attack_tactics,
    parse_enterprise_attack_techniques,
    parse_file_paths,
    parse_google_adsense_ids,
    parse_google_analytics_ids,
    parse_imphashes_,
    parse_ipv4_addresses,
    parse_ipv4_cidrs,
    parse_ipv6_addresses,
    parse_mac_addresses,
    parse_md5s,
    parse_mobile_attack_tactics,
    parse_mobile_attack_techniques,
    parse_pre_attack_tactics,
    parse_pre_attack_techniques,
    parse_registry_key_paths,
    parse_sha1s,
    parse_sha256s,
    parse_sha512s,
    parse_ssdeeps,
    parse_tlp_labels,
    parse_urls,
    parse_user_agents,
    parse_xmpp_addresses,
    prepare_text,
)

# Library convention: attach a NullHandler so importing the package never
# emits "no handlers could be found" warnings when the consuming app has not
# configured logging. Apps opt in to ioc_finder's logs by configuring the
# "ioc_finder" logger (or root) themselves.
logging.getLogger(__name__).addHandler(logging.NullHandler())

__all__ = [
    "DEFAULT_IOC_TYPES",
    "SUPPORTED_IOC_TYPES",
    "find_iocs",
    "parse_asns",
    "parse_authentihashes_",
    "parse_bitcoin_addresses",
    "parse_complete_email_addresses",
    "parse_cves",
    "parse_domain_names",
    "parse_email_addresses",
    "parse_enterprise_attack_tactics",
    "parse_enterprise_attack_techniques",
    "parse_file_paths",
    "parse_google_adsense_ids",
    "parse_google_analytics_ids",
    "parse_imphashes_",
    "parse_ipv4_addresses",
    "parse_ipv4_cidrs",
    "parse_ipv6_addresses",
    "parse_mac_addresses",
    "parse_md5s",
    "parse_mobile_attack_tactics",
    "parse_mobile_attack_techniques",
    "parse_pre_attack_tactics",
    "parse_pre_attack_techniques",
    "parse_registry_key_paths",
    "parse_sha1s",
    "parse_sha256s",
    "parse_sha512s",
    "parse_ssdeeps",
    "parse_tlp_labels",
    "parse_urls",
    "parse_user_agents",
    "parse_xmpp_addresses",
    "prepare_text",
]
